
/** @file modone.h
 * 
 * @brief Team members: Qitao Xu, Zhe Wang, Jiangnan Liu
 * 		  The header file was generated by calculating automatically.
 * 		  The use case for this header file is  
 * @par       
 */ 

#ifndef MODONE_H
#define MODONE_H

struct task{
	unsigned long period; /*period of task*/
	struct subtask{
		unsigned long subperiod;/*period of subtask*/
	};
};
int8_t max8(int8_t num1, int8_t num2);

#endif /* MODONE_H */